<?php

namespace App\Domains\Identity\Services;

use App\Domains\Identity\Models\User;
use Illuminate\Support\Str;
use PragmaRX\Google2FA\Google2FA;

/**
 * TOTP enrollment and verification. A secret generated by enable() is not
 * active until confirm() validates one real code from the authenticator
 * app — this is what stops an admin from silently switching MFA "on" for a
 * user without them ever having actually enrolled a device.
 */
class TwoFactorAuthenticationService
{
    protected Google2FA $engine;

    public function __construct()
    {
        $this->engine = new Google2FA;
    }

    /**
     * Start enrollment: generate and store a new secret, unconfirmed. Safe
     * to call again before confirm() — it just replaces the pending secret.
     */
    public function enable(User $user): string
    {
        $secret = $this->engine->generateSecretKey();

        $user->forceFill([
            'two_factor_secret' => $secret,
            'two_factor_recovery_codes' => null,
            'two_factor_confirmed_at' => null,
            'two_factor_enabled' => false,
        ])->save();

        return $secret;
    }

    /**
     * The standard otpauth:// URI an authenticator app (or a QR-rendering
     * component) turns into a scannable code. Google2FA's core package
     * doesn't render QR images itself — that's deliberately left to the
     * frontend, so this only builds the URI it needs.
     */
    public function qrCodeUrl(User $user): string
    {
        $issuer = rawurlencode((string) config('app.name'));
        $label = rawurlencode($issuer.':'.$user->email);

        $query = http_build_query([
            'secret' => $user->two_factor_secret,
            'issuer' => config('app.name'),
            'algorithm' => 'SHA1',
            'digits' => 6,
            'period' => 30,
        ]);

        return "otpauth://totp/{$label}?{$query}";
    }

    /**
     * Verify one code against the pending secret and, if valid, activate
     * MFA and issue a fresh set of one-time recovery codes.
     *
     * @return array<string>|null the recovery codes, or null if the code didn't verify
     */
    public function confirm(User $user, string $code): ?array
    {
        if (! $user->two_factor_secret || ! $this->engine->verifyKey($user->two_factor_secret, $code)) {
            return null;
        }

        $recoveryCodes = $this->generateRecoveryCodes();

        $user->forceFill([
            'two_factor_recovery_codes' => $recoveryCodes,
            'two_factor_confirmed_at' => now(),
            'two_factor_enabled' => true,
        ])->save();

        return $recoveryCodes;
    }

    public function disable(User $user): void
    {
        $user->forceFill([
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null,
            'two_factor_confirmed_at' => null,
            'two_factor_enabled' => false,
        ])->save();
    }

    public function isEnabled(User $user): bool
    {
        return $user->two_factor_confirmed_at !== null;
    }

    /**
     * Verify a login-time TOTP code against the user's confirmed secret.
     */
    public function verify(User $user, string $code): bool
    {
        if (! $this->isEnabled($user) || ! $user->two_factor_secret) {
            return false;
        }

        return $this->engine->verifyKey($user->two_factor_secret, $code);
    }

    /**
     * Verify and consume a recovery code — each one works exactly once.
     */
    public function verifyRecoveryCode(User $user, string $code): bool
    {
        $codes = $user->two_factor_recovery_codes ?? [];
        $index = array_search(strtoupper(trim($code)), $codes, true);

        if ($index === false) {
            return false;
        }

        unset($codes[$index]);

        $user->forceFill([
            'two_factor_recovery_codes' => array_values($codes),
        ])->save();

        return true;
    }

    public function regenerateRecoveryCodes(User $user): array
    {
        $codes = $this->generateRecoveryCodes();

        $user->forceFill(['two_factor_recovery_codes' => $codes])->save();

        return $codes;
    }

    protected function generateRecoveryCodes(): array
    {
        return collect(range(1, 8))
            ->map(fn () => Str::upper(Str::random(4).'-'.Str::random(4)))
            ->all();
    }
}
